{{- if .Values.secretsStore.create }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretsStore.providerClassName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "{{ .Values.secretsStore.awsSecretObjectName }}"
        objectType: secretsmanager
        jmesPath:
          - path: PG_HOST
            objectAlias: PG_HOST
          - path: PG_PORT
            objectAlias: PG_PORT
          - path: PG_USERNAME
            objectAlias: PG_USERNAME
          - path: PG_PASSWORD
            objectAlias: PG_PASSWORD
          - path: PG_DB
            objectAlias: PG_DB
          - path: REDIS_HOST
            objectAlias: REDIS_HOST
  secretObjects:
    - secretName: {{ .Values.secretsStore.secretName }}
      type: Opaque
      data:
        - key: PG_HOST
          objectName: PG_HOST
        - key: PG_PORT
          objectName: PG_PORT
        - key: PG_USERNAME
          objectName: PG_USERNAME
        - key: PG_PASSWORD
          objectName: PG_PASSWORD
        - key: PG_DB
          objectName: PG_DB
        - key: REDIS_HOST
          objectName: REDIS_HOST
{{- end }}
