apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: actions-runner-controller-secrets-store
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    region: ap-northeast-2
    objects: |
      - objectName: # env github ci-bot
        objectType: secretsmanager
        jmesPath:
          - path: # token path
            objectAlias: # github token
  secretObjects:
    - secretName: actions-runner-controller-secret
      type: Opaque
      data:
        - key: # github token
          objectName: # github token
