apiVersion: v2
name: kube-prometheus-stack
description: kube-prometheus-stack collects Kubernetes manifests, Grafana dashboards, and Prometheus rules combined with documentation and scripts
type: application
version: 67.0.0
appVersion: v0.79.0
keywords:
  - operator
  - prometheus
  - grafana
  - monitoring
home: https://github.com/prometheus-operator/kube-prometheus
sources:
  - https://github.com/prometheus-community/helm-charts
  - https://github.com/prometheus-operator/kube-prometheus
dependencies:
  - name: kube-prometheus-stack
    version: 67.0.0
    repository: https://prometheus-community.github.io/helm-charts
