{{- if .Values.applications.actionsRunner.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner
  namespace: {{ $.Values.argocd.namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $.Values.applications.namespace }}
    server: https://kubernetes.default.svc
  project: {{ $.Values.argocd.project }}
  source:
    path: helm-charts/actions-runner-system/actions-runner/{{ $.Values.applications.actionsRunner.version }}
    repoURL: git@github.com:smsm8898/infra-apps
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - values-{{ $.Values.environment }}.yaml
  syncPolicy:
    automated:
      {{- toYaml $.Values.argocd.syncPolicy.automated | nindent 12 }}
    syncOptions:
      {{- toYaml $.Values.argocd.syncPolicy.syncOptions | nindent 12 }}
{{- end }}
